pipeline {
  agent any   // Run on any available Jenkins agent

  stages {
    stage('Code Checkout') {
      steps {
        // Clone the GitHub repository (main branch)
        git branch: 'main', url: 'https://github.com/Oren1984/terraform-aws-lab.git'
      }
    }

    stage('Terraform init') {
      steps {
        // Initialize Terraform (download providers, configure backend, etc.)
        sh 'terraform init'
      }
    }

    stage('Terraform Apply') {
      steps {
        // Inject AWS credentials only for this block using Jenkins credentials
        withCredentials([
          string(credentialsId: 'aws-access-key-id',     variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key-id', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          // Set AWS region and run Terraform apply automatically
          sh '''
            export AWS_DEFAULT_REGION="us-east-1"
            terraform apply -auto-approve
          '''
        }
      }
    }
  }
}

